# $RuOBSD: Makefile,v 1.3 2011/08/03 08:28:33 dinar Exp $

     SUBDIR += cvsd
     SUBDIR += libbegemot
     SUBDIR += p5-Class-Mix
     SUBDIR += p5-Data-Float
     SUBDIR += p5-Data-Integer
     SUBDIR += p5-Module-Runtime
     SUBDIR += p5-Params-Classify
     SUBDIR += p5-Scalar-String
     SUBDIR += p5-Scalar-List-Utils
     SUBDIR += p5-parent

.include <bsd.port.subdir.mk>
