# $RuOBSD  $

COMMENT=	ISA relationship with base classes at compile time

MODULES=	cpan
DISTNAME=	parent-0.223

MASTER_SITES=http://search.cpan.org/CPAN/authors/id/C/CO/CORION/

CATEGORIES=	devel


# Artistic/GPL
PERMIT_PACKAGE_CDROM=	Yes
PERMIT_PACKAGE_FTP=	Yes
PERMIT_DISTFILES_CDROM=	Yes
PERMIT_DISTFILES_FTP=	Yes


.include <bsd.port.mk>
