# $RuOBSD  $

COMMENT=	Perl module for the Eksblowfish block cipher

MODULES=	cpan
DISTNAME=	Crypt-Eksblowfish-0.008

CATEGORIES=	security

# Artistic/GPL
PERMIT_PACKAGE_CDROM=	Yes
PERMIT_PACKAGE_FTP=	Yes
PERMIT_DISTFILES_CDROM=	Yes
PERMIT_DISTFILES_FTP=	Yes

CONFIGURE_STYLE=	modbuild

RUN_DEPENDS=		::devel/p5-Class-Mix \
			::devel/p5-parent

.include <bsd.port.mk>
