# $RuOBSD: Makefile,v 1.3 2011/06/10 09:17:53 dinar Exp $

COMMENT=	Argument type classification

MODULES=	cpan
DISTNAME=	Params-Classify-0.011

CATEGORIES=	devel

CONFIGURE_STYLE=	modbuild

RUN_DEPENDS=	devel/p5-parent
BUILD_DEPENDS=	${RUN_DEPENDS}


# Artistic/GPL
PERMIT_PACKAGE_CDROM=	Yes
PERMIT_PACKAGE_FTP=	Yes
PERMIT_DISTFILES_CDROM=	Yes
PERMIT_DISTFILES_FTP=	Yes


.include <bsd.port.mk>
