# $RuOBSD: Makefile,v 1.3 2011/06/10 09:27:13 dinar Exp $

COMMENT=	Interfaces between strings and the rest of the system

MODULES=	cpan
DISTNAME=	Encode-2.42

CATEGORIES=	converters

CONFIGURE_STYLE= perl

MAINTAINER=	dinar@yantel.ru

# Artistic/GPL
PERMIT_PACKAGE_CDROM=	Yes
PERMIT_PACKAGE_FTP=	Yes
PERMIT_DISTFILES_CDROM=	Yes
PERMIT_DISTFILES_FTP=	Yes

.include <bsd.port.mk>
