#	$RuOBSD: Makefile.OpenBSD,v 1.3 2001/11/18 07:28:10 form Exp $

PROG=	tunneld
SRCS=	tunneld.c
MAN=	tunneld.8

COPTS=	-Wall -Werror -DCRYPT -DNAT -I${.CURDIR}/../libalias
LDADD=	-lutil -L${.CURDIR}/../libalias/obj -L${.CURDIR}/../libalias -lalias
DPADD=	${LIBUTIL}

BINDIR?=/usr/local/sbin

.if defined(OPVER) && ${OPVER} > 2.8
COPTS+=	-DHAS_PIDFILE
.else
SRCS+=	pidfile.c
.endif

.if defined(OPVER) && ${OPVER} < 2.8
COPTS+=	-DTUN_AF_HOSTORDER
.endif
