#	$RuOBSD: Makefile.NetBSD,v 1.2 2001/11/15 11:26:48 form Exp $

PROG=	tunneld
SRCS=	tunneld.c pidfile.c
MAN=	tunneld.8

COPTS=	-Wall -Werror -DCRYPT -DNAT -I${.CURDIR}/../libalias
LDADD=	-L${.CURDIR}/../libalias/obj -L${.CURDIR}/../libalias -lalias

BINDIR?=/usr/local/sbin
