#	$RuOBSD: Makefile.NetBSD,v 1.1 2001/11/15 03:54:27 form Exp $

PROG=	tunneld
SRCS=	tunneld.c pidfile.c
MAN=

COPTS=	-Wall -Werror -DCRYPT -DNAT -I${.CURDIR}/../libalias
LDADD=	-L${.CURDIR}/../libalias/obj -L${.CURDIR}/../libalias -lalias

BINDIR?=/usr/local/sbin
