.\"	$RuOBSD: tunneld.8,v 1.2 2001/11/20 03:05:58 form Exp $
.\"
.\" Copyright (c) 2001 Denis Afonin & Oleg Safiullin
.\" All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice unmodified, this list of conditions, and the following
.\"    disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND
.\" ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE
.\" FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
.\" DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
.\" OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
.\" LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
.\" OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.Dd November 18, 2001
.Dt TUNNELD 8
.Os
.Sh NAME
.Nm tunneld
.Nd IP over IP tunnel daemon
.Sh SYNOPSIS
.Nm tunneld
.Op Fl dEmNsuv
.Op Fl b Ar src
.Op Fl p Ar proto
.Op Fl t Ar tun
.Ar dst
.Op Ar local remote Op Ar mask
.Sh DESCRIPTION
The
.Nm
is an IP over IP tunnelling daemon.
The
.Nm
establishes nos (also known as ka9q) style tunnel with host
.Em dst ,
using
.Xr tun 4
network interface driver.
The
.Xr tun 4
interface is configured with
.Em local ,
.Em remote
addresses and netmask
.Em mask ,
if specified.
The
.Nm
is fully compatible with
.Xr gif 4
interface driver,
.Fx
.Xr nos-tun 8
daemon and Cisco nos style tunnels (except for
.Nm
.Fl E
case).
.Pp
The options are follows:
.Bl -tag -width Ds
.It Fl b Ar src
Specify the source address to transmit from on hosts with multiple
interfaces or aliased addresses.
.It Fl d
Refuse all incoming packets
where an aliasing link doesn't already exist.
.It Fl E
Turn on traffic encryption.
Currently only weak XOR encryption is supported.
.It Fl m
Tell the network address translation engine to attempt to avoid changing
the port number on outgoing packets.
This is useful if you want to support protocols such as RPC and LPD which
require connections to come from a well known port.
.It Fl N
Turn network address translation on.
.It Fl p Ar proto
Specify the protocol used for establishing the tunnel.
Available protocols are 4 (ipencap) and 94 (ipip).
Default is 94 (ipip).
.It Fl s
Tell the network address translation engine to create a socket so that it
can guarantee a correct incoming FTP data or IRC connection.
.It Fl t Ar tun
Specify the tunnel interface used for tunneled traffic.
By default
.Nm
will find first available
.Xr tun 4
interface.
.It Fl u
Tell the network address translation engine to alter only outgoing packets
with an unregistered source address.
According to RFC 1918, unregistered source addresses
are 10.0.0.0/8, 172.16.0.0/12 and 192.168.0.0/16.
.It Fl v
Verbose mode.
This option will prevent
.Nm
from detaching from the controlling terminal and will turn logging
to stderr on.
.El
.Sh EXAMPLES
Configuration examples:
.Pp
(192.168.1.0/24) - host A: 1.2.3.4 <-> host B: 5.6.7.8 - (192.168.2.0/24)
.Pp
On host A:
.Bd -literal -offset 3n -compact
# tunneld 5.6.7.8 192.168.1.1 192.168.2.1
# route add -net 192.168.2.0/24 192.168.2.1
.Ed
.Pp
On host B:
.Bd -literal -offset 3n -compact
# tunneld 1.2.3.4 192.168.2.1 192.168.1.1
# route add -net 192.168.1.0/24 192.168.1.1
.Ed
.Pp
OR
.Pp
(192.168.1.0/24) - host A: 1.2.3.4 <-> host B: 5.6.7.8 - Internet (NAT)
.Pp
On host A:
.Bd -literal -offset 3n -compact
# tunneld -Nmus 5.6.7.8 5.6.7.10 5.6.7.9
# route add -host 5.6.7.8 1.2.3.1
# route change default 5.6.7.9
.Ed
.Pp
On host B:
.Bd -literal -offset 3n -compact
# tunneld 1.2.3.4 5.6.7.9 5.6.7.10
.Ed
.Sh BUGS
IPv6 protocol is not supported.
.Pp
Kernels with integrated KAME IPv6 stack may conflict with 4 (ipip)
protocol.
If this is the case, use 94 protocol.
.Pp
PPTP protocol doesn't work in network address translation mode when more
than one client connects to the same external server at the same time,
because PPTP requires a single TCP control connection to be established
between any two IP addresses.
.Pp
Currently, encryption method used by
.Nm
(with
.Fl E
flag specified) is too weak.
Never use
.Nm
to transfer confidential data.
.Sh FILES
.Bl -tag -width /var/run/tunneld-tunX.pid -compact
.It Pa /var/run/tunneld-tunX.pid
process ID of running
.Nm
using tunX interface.
.El
.Sh SEE ALSO
.Xr ipsec 4 ,
.Xr netintro 4 ,
.Xr tun 4 ,
.Xr ifconfig 8
.Sh HISTORY
.An Oleg Safiullin Aq form@openbsd.ru
wrote the
.Nm
program for
.Ox
and then makes it support
.Fx
and
.Nx .
.Pp
.An Denis Afonin Aq dfa@openbsd.ru .
