# $RuOBSD$

DISTNAME=	qutim-${VERSION}
VERSION=	0.2.0

EXTRACT_SUFX=	.tar.bz2

CATEGORIES=	net
MASTER_SITES=	http://www.qutim.org/uploads/src/

MAINTAINER=	dinar@yantel.ru
COMMENT=	A Qt4-based multiprotocol IM client with advanced features

PERMIT_PACKAGE_CDROM=   Yes
PERMIT_PACKAGE_FTP=     Yes
PERMIT_DISTFILES_CDROM= Yes
PERMIT_DISTFILES_FTP=   Yes


