#!/bin/sh
# $RuOBSD$
#
# Copyright (c) 2004 Alexander Yurchenko <grange@openbsd.ru>
#
# Permission to use, copy, modify, and distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
# ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
# ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
# OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
#

#
# Script for finding files that don't belong to the base distribution
# anymore. Before using it you should have a full distribution which can
# be created after make build with the following command:
#
# cd /usr/src/etc && env DESTDIR=/usr/dest make distribution
#

: ${DESTDIR=/usr/dest}

if [ ! -f $DESTDIR/bin/sh ]; then
	echo "Can't find distribution in $DESTDIR"
	exit 1
fi

if [ ! -d $SRCDIR ]; then
	echo "Couldn't find source tree in $SRCDIR, you should set SRCDIR"
	exit 1
fi

DIRS="altroot bin sbin stand usr/bin usr/games usr/include usr/lib \
    usr/libdata usr/libexec usr/lkm usr/mdec usr/sbin usr/share"

for DIR in $DIRS
do
	find /$DIR/ -exec test ! -e $DESTDIR{} \; -print
done
