# $RuOBSD$

COMMENT=	Perl module for runtime module handling

MODULES=	cpan
DISTNAME=	Module-Runtime-0.007

CATEGORIES=	devel

CONFIGURE_STYLE=	modbuild

BUILD_DEPENDS=	::devel/p5-parent
RUN_DEPENDS=	${BUILD_DEPENDS}
# Artistic/GPL
PERMIT_PACKAGE_CDROM=	Yes
PERMIT_PACKAGE_FTP=	Yes
PERMIT_DISTFILES_CDROM=	Yes
PERMIT_DISTFILES_FTP=	Yes


.include <bsd.port.mk>
