# $RuOBSD$

COMMENT=	Perl module for dynamic class mixing

MODULES=	cpan
DISTNAME=	Class-Mix-0.003

CATEGORIES=	devel

CONFIGURE_STYLE=	modbuild

BUILD_DEPENDS=	::devel/p5-parent
RUN_DEPENDS=	${BUILD_DEPENDS}

# Artistic/GPL
PERMIT_PACKAGE_CDROM=	Yes
PERMIT_PACKAGE_FTP=	Yes
PERMIT_DISTFILES_CDROM=	Yes
PERMIT_DISTFILES_FTP=	Yes


.include <bsd.port.mk>
