# $RuOBSD$

COMMENT=		"development library used for p11"

DISTNAME=		libbegemot-1.11
CATEGORIES=		devel

# GPL
PERMIT_PACKAGE_CDROM=	Yes
PERMIT_PACKAGE_FTP=	Yes
PERMIT_DISTFILES_CDROM=	Yes
PERMIT_DISTFILES_FTP=	Yes

SHARED_LIBS=		begemot 1.11

MASTER_SITES=		http://people.freebsd.org/~harti/libbegemot/

USE_GMAKE=		Yes
USE_LIBTOOL=		Yes

CONFIGURE_STYLE=	gnu

.include <bsd.port.mk>
