#!/bin/sh
# $RuOBSD$
#
# Pre/post-installation setup of sqmgrlog

# exit on errors, use a sane path and install prefix
#
set -e
PATH=/bin:/usr/bin:/sbin:/usr/sbin
PREFIX=${PKG_PREFIX:-/usr/local}
CONFIG_FILE=/etc/squid/sqmgrlog.conf
SAMPLE_CONFIG_FILE=${PREFIX}/share/examples/sqmgrlog/sqmgrlog.conf

# Function: tell the user what s/he needs to do to use the port just installed
#
do_notice_conf()
{
	echo
	echo "+---------------"
	echo "| The existing $1 configuration file,"
	echo "| ${CONFIG_FILE} have NOT been changed."
	echo "| You may want to compare it to the current"
	echo "| sample ${SAMPLE_CONFIG_FILE}, and update"
	echo "| your configuration files as needed."
	echo "+---------------"
	echo
}

# Function: install the system configuration files from the samples
#
do_install_conf()
{
	install -o root -g wheel -m 755 -d /etc/squid
	install -o root -g wheel -m 444 ${SAMPLE_CONFIG_FILE} ${CONFIG_FILE}
	echo
	echo "+---------------"
	echo "| The $1 configuration file, ${CONFIG_FILE},"
	echo "| have been installed. Please view this file and change"
	echo "| the configuration to meet your needs."
	echo "+---------------"
	echo
}

# verify proper execution
#
if [ $# -ne 2 ]; then
	echo "usage: $0 distname { PRE-INSTALL | POST-INSTALL }" >&2
	exit 1
fi

# Verify/process the command
#
case $2 in
	PRE-INSTALL)
		: nothing to pre-install for this port
		;;
	POST-INSTALL)
		if [ -f ${CONFIG_FILE} ]; then
			do_notice_conf $1
		else
			do_install_conf $1
		fi
		;;
	*)
		echo "usage: $0 distname { PRE-INSTALL | POST-INSTALL }" >&2
		exit 1
		;;
esac

exit 0
