#!/bin/sh
# $OpenBSD$

echo "+---------------"
echo "| To completely deinstall the $1 package you need to perform"
echo "| these steps as root:"
echo "| rmuser ${DRWEBUSER}"
echo "| rm -rf /var/drweb"
echo "| rm -rf /etc/drweb"
echo "| delete any cron jobs"
echo "| disable drwebd if necessary in /etc/rc.conf.local"
echo "+---------------"

exit 0
