# $RuOBSD$

COMMENT=	Details of the floating point data type

MODULES=	cpan
DISTNAME=	Data-Float-0.010


CATEGORIES=	devel

CONFIGURE_STYLE=	modbuild

# Artistic/GPL
PERMIT_PACKAGE_CDROM=	Yes
PERMIT_PACKAGE_FTP=	Yes
PERMIT_DISTFILES_CDROM=	Yes
PERMIT_DISTFILES_FTP=	Yes


.include <bsd.port.mk>
