# $RuOBSD: Makefile,v 1.1 2004/11/16 16:49:19 form Exp $

PROG=	kevent
MAN=

CFLAGS+=-W -Wall -Werror -Winline -Wshadow -Wcast-qual -Wpointer-arith
CFLAGS+=-Wmissing-declarations -Wmissing-prototypes -Wstrict-prototypes
CFLAGS+=-pedantic

.include <bsd.prog.mk>
