# $RuOBSD$

COMMENT=	Perl module for details of the native integer data type

MODULES=	cpan
DISTNAME=	Data-Integer-0.004

CATEGORIES=	devel

CONFIGURE_STYLE=	modbuild

# Artistic/GPL
PERMIT_PACKAGE_CDROM=	Yes
PERMIT_PACKAGE_FTP=	Yes
PERMIT_DISTFILES_CDROM=	Yes
PERMIT_DISTFILES_FTP=	Yes


.include <bsd.port.mk>
