# $RuOBSD: Makefile,v 1.1.1.1 2008/07/12 19:00:53 form Exp $

     SUBDIR += ircd-hybrid
     SUBDIR += ircyka
     SUBDIR += licq
     SUBDIR += sim-im
     SUBDIR += sim-im-devel
     SUBDIR += xchat1

.include <bsd.port.subdir.mk>
