# $RuOBSD: Makefile,v 1.2 2008/09/04 12:06:34 form Exp $

     SUBDIR += ircyka
     SUBDIR += licq
     SUBDIR += sim-im
     SUBDIR += sim-im-devel
     SUBDIR += xchat1

.include <bsd.port.subdir.mk>
