# $RuOBSD: Makefile,v 1.3 2009/01/29 05:35:59 form Exp $

     SUBDIR += ircyka
     SUBDIR += licq
     SUBDIR += qutim
     SUBDIR += sim-im
     SUBDIR += sim-im-devel
     SUBDIR += xchat1

.include <bsd.port.subdir.mk>
