# $RuOBSD$

LIB=	acldb
SRCS=	acldb_add.c acldb_aflags.c acldb_close.c acldb_creat.c acldb_del.c \
	acldb_find.c acldb_flags.c acldb_get.c acldb_open.c acldb_sync.c \
	acldb_update.c

.include <bsd.lib.mk>
