# $RuOBSD$

SRCS=		koi10x16b koi8x13 koi10x20 koi8x16 koi12x24 koi8x16b \
		koi12x24b koi9x15 koi5x8 koi9x15b koi6x10 koi9x18 koi6x13 \
		koi9x18b koi6x13b koinil2 koi6x9 screen8x16 koi7x14 \
		screen8x16b koi7x14b

FONTSSUBDIR=	misc
FIXED=		Yes

.include "../Makefile.inc"
