# $FreeBSD: ports/net/ripetools/Makefile,v 1.7 2000/04/09 18:13:23 cpiazza Exp $
# $RuOBSD$

DISTNAME=	ripe-whois-tools-2.4
PKGNAME=	ripetools-2.4
CATEGORIES=	net
MASTER_SITES=	ftp://ftp.ripe.net/tools/

MAINTAINER=	form@openbsd.ru

PERMIT_PACKAGE_CDROM=	Yes
PERMIT_PACKAGE_FTP=	Yes
PERMIT_DISTFILES_CDROM=	Yes
PERMIT_DISTFILES_FTP=	Yes

WRKDIST=	${WRKDIR}

.include <bsd.port.mk>
