# $RuOBSD: Makefile,v 1.2 2002/05/15 04:37:15 form Exp $

COMMENT=	"Bohlin's IrDA utilities"

DISTNAME=	birda-1.00
PKGNAME=	${DISTNAME}
CATEGORIES=	comms
MASTER_SITES=	ftp://ftp.augustsson.net/pub/netbsd/

MAINTAINER=	Pavel Korovin <pvk@oxygene.ru>

PERMIT_PACKAGE_CDROM=	Yes
PERMIT_PACKAGE_FTP=	Yes
PERMIT_DISTFILES_CDROM=	Yes
PERMIT_DISTFILES_FTP=	Yes

FAKE_FLAGS=	PREFIX="${PREFIX}" MANDIR="${PREFIX}/man/cat"

.include <bsd.port.mk>
