# $RuOBSD: Makefile,v 1.2 2010/11/01 16:58:50 dinar Exp $

COMMENT=	A selection of general-utility scalar subroutines

MODULES=	cpan
DISTNAME=	Scalar-List-Utils-1.23

CATEGORIES=	devel

#CONFIGURE_STYLE=	modbuild

# Artistic/GPL
PERMIT_PACKAGE_CDROM=	Yes
PERMIT_PACKAGE_FTP=	Yes
PERMIT_DISTFILES_CDROM=	Yes
PERMIT_DISTFILES_FTP=	Yes


.include <bsd.port.mk>
