#!/bin/sh
# $RuOBSD$
#
# mnogosearch de-installation

PATH=/bin:/usr/bin:/sbin:/usr/sbin
PREFIX=${PKG_PREFIX:-/usr/local}
CONFIG_DIR=${SYSCONFDIR}/mnogosearch
MNOGOSEARCHDIR=${MNOGOSEARCHDIR}

echo
echo "+---------------"
echo "| To completely deinstall the $1 package you need to perform"
echo "| these steps as root:"
echo "|"
echo "|           rm -rf $CONFIG_DIR"
echo "|           rm -rf $MNOGOSEARCHDIR"
echo "|"
echo "| Do not do this if you plan on re-installing $1"
echo "| at some future time."
echo "+---------------"
echo

exit 0
