#!/bin/sh
# $RuOBSD$
#
# Pre/post-installation setup of mnogosearch

PATH=/bin:/usr/bin:/sbin:/usr/sbin
PREFIX=${PKG_PREFIX:-/usr/local}
CONFIG_DIR=${SYSCONFDIR}/mnogosearch
SAMPLE_CONFIG_DIR=$PREFIX/share/examples/mnogosearch
MNOGOSEARCHDIR=${MNOGOSEARCHDIR}

do_mnogosearchdir_install()
{
  install -d -o www -g www -m 755 $MNOGOSEARCHDIR
  install -d -o www -g www -m 777 $MNOGOSEARCHDIR/cache
  install -d -o www -g www -m 755 $MNOGOSEARCHDIR/raw
  install -d -o www -g www -m 755 $MNOGOSEARCHDIR/splitter
  install -d -o www -g www -m 755 $MNOGOSEARCHDIR/tree
}

do_notice_conf()
{
  echo
  echo "+---------------"
  echo "| The existing $1 configuration files"
  echo "| in $CONFIG_DIR have NOT been changed."
  echo "| You may want to compare them to the current samples in"
  echo "| $SAMPLE_CONFIG_DIR, and update your configuration"
  echo "| files as needed."
  echo "+---------------"
  echo
}

do_install_conf()
{
  install -d -o root -g wheel -m 755 $CONFIG_DIR
  install -o root -g wheel -m 644 $SAMPLE_CONFIG_DIR/indexer.conf-dist \
      $CONFIG_DIR/indexer.conf
  install -o root -g wheel -m 644 $SAMPLE_CONFIG_DIR/search.htm-dist \
      $CONFIG_DIR/search.htm
  install -o root -g wheel -m 644 $SAMPLE_CONFIG_DIR/spelld.conf-dist \
      $CONFIG_DIR/spelld.conf
  echo
  echo "+---------------"
  echo "| The $1 configuration files have been installed"
  echo "| in $CONFIG_DIR."
  echo "| Please view these files and change the configuration"
  echo "| to meet your needs."
  echo "+---------------"
  echo
}

# verify proper execution
#
if [ $# -ne 2 ]; then
    echo "usage: $0 distname { PRE-INSTALL | POST-INSTALL }" >&2
    exit 1
fi

# Verify/process the command
#
case $2 in
    PRE-INSTALL)
	;;
    POST-INSTALL)
#	if [ ! -d $MNOGOSEARCHDIR ]; then
#	   do_mnogosearchdir_install
#	fi
	if [ ! -d $CONFIG_DIR ]; then
	   do_install_conf $1
	elif [ ! -f $CONFIG_DIR/indexer.conf ]; then
	   do_install_conf $1
	else
	   do_notice_conf $1
	fi
	;;
    *)
	echo "usage: $0 distname { PRE-INSTALL | POST-INSTALL }" >&2
	exit 1
	;;
esac

exit 0
