# $RuOBSD$

COMMENT=	XS interface for a portable traditional crypt function

MODULES=	cpan
DISTNAME=	Crypt-UnixCrypt_XS-0.09

CATEGORIES=	security

# Artistic/GPL
PERMIT_PACKAGE_CDROM=	Yes
PERMIT_PACKAGE_FTP=	Yes
PERMIT_DISTFILES_CDROM=	Yes
PERMIT_DISTFILES_FTP=	Yes

CONFIGURE_STYLE=	perl


.include <bsd.port.mk>
