# $RuOBSD  $

COMMENT=	Perl module for string aspects of scalars

MODULES=	cpan
DISTNAME=	Scalar-String-0.001

CATEGORIES=	devel

CONFIGURE_STYLE=	modbuild

# Artistic/GPL
PERMIT_PACKAGE_CDROM=	Yes
PERMIT_PACKAGE_FTP=	Yes
PERMIT_DISTFILES_CDROM=	Yes
PERMIT_DISTFILES_FTP=	Yes


.include <bsd.port.mk>
