#	$RuOBSD: Makefile,v 1.1 2001/01/16 04:24:56 form Exp $

SUBDIR=	sbniconfig

install-driver:
	@cd ${.CURDIR}/driver; sh install.sh

update-driver:
	@cd ${.CURDIR}/driver; sh install.sh

.include <bsd.subdir.mk>
