# $RuOBSD$ 

     SUBDIR += p5-Authen-DecHpwd
     SUBDIR += p5-Authen-Passphrase
     SUBDIR += p5-Crypt-Eksblowfish
     SUBDIR += p5-Crypt-MySQL
     SUBDIR += p5-Crypt-UnixCrypt_XS
     SUBDIR += p5-Data-Entropy
     SUBDIR += p5-Mail-Sendmail

.include <bsd.port.subdir.mk>
