# $RuOBSD$

PROG=	tree
MAN=

CFLAGS+=-Wall -Werror -Winline -Wshadow -Wcast-qual -Wpointer-arith
CFLAGS+=-Wmissing-declarations -Wmissing-prototypes -Wstrict-prototypes
CFLAGS+=-pedantic

.include <bsd.prog.mk>
