#!/bin/sh
# $RuOBSD$
#
# clamav de-installation

set -e
PATH=/bin:/usr/bin:/sbin:/usr/sbin
PREFIX=${PKG_PREFIX:-/usr/local}
CONFIG_DIR=${SYSCONFDIR}/clamav
CLAM_DIR=${CLAM_DIR}
CLAM_USER=${CLAM_USER}
CLAM_GROUP=${CLAM_GROUP}

if [ "${PKG_DELETE_EXTRA}" != Yes ]; then
	echo
	echo "+---------------"
	echo "| To completely deinstall the $1 package you need to perform"
	echo "| this step as root:"
	echo "|"
	echo "|		userdel ${CLAM_USER}"
	echo "|		groupdel ${CLAM_GROUP}"
	echo "|		rm -rf ${CONFIG_DIR}/clamav"
	echo "|		rm -rf ${CLAM_DIR}"
	echo "|"
	echo "| Do not do this if you plan on re-installing $1"
	echo "| at some future time."
	echo "+---------------"
	echo
fi

exit 0
