# $OpenBSD: Makefile,v 1.18 2002/05/03 16:20:19 brad Exp $
# $RuOBSD$

COMMENT=		"GUI toolkit for X11"

DISTNAME=		xforms-0.9999
CATEGORIES=		x11
NEED_VERSION=		1.527
MASTER_SITES=		ftp://ncmir.ucsd.edu/pub/xforms/OpenSource/
EXTRACT_SUFX=		.tgz

HOMEPAGE=		http://world.std.com/~xforms/

PERMIT_PACKAGE_CDROM=	Yes
PERMIT_PACKAGE_FTP=	Yes
PERMIT_DISTFILES_CDROM=	Yes
PERMIT_DISTFILES_FTP=	Yes

MAINTAINER=		Oleg Safiullin <form@openbsd.org>

USE_X11=		Yes
CONFIGURE_STYLE=	imake

.include <bsd.port.mk>
