# $RuOBSD: Makefile,v 1.2 2004/03/17 09:28:17 form Exp $

COMMENT=		"IP/IPv6 traffic collector"

DISTNAME=		cnupm-3.2
CATEGORIES=		net

HOMEPAGE=		http://pdp-11.org.ru/~form/cnupm

PERMIT_PACKAGE_CDROM=	Yes
PERMIT_PACKAGE_FTP=	Yes
PERMIT_DISTFILES_CDROM=	Yes
PERMIT_DISTFILES_FTP=	Yes

MASTER_SITES=		${HOMEPAGE}/files/

.include <bsd.port.mk>
