#!/bin/sh
# $OpenBSD$

echo "+---------------"
echo "| To completely deinstall the $1 package you need to perform"
echo "| these steps as root:"
echo "| Delete drweb daemon port"
echo "| rmuser ${DRWEBUSER}"
echo "| rm -rf /etc/drweb/*.conf"
echo "| disable drweb-smf if necessary in /etc/rc.conf.local"
echo "+---------------"

exit 0
