#!/bin/sh
# $OpenBSD$

PATH=/bin:/usr/bin:/sbin:/usr/sbin

create_group()
{
        echo -n "Checking group ${DRWEBGROUP}: "

        groupinfo -e ${DRWEBGROUP} && {
                echo "OK, group already exists." >&2
                return
        }
        echo -n "group does not exist. Creating... "
        groupadd -g ${DRWEBID} ${DRWEBGROUP} || {
                echo "ERR, cannot append to ${SYSCONFDIR}/group" >&2
                exit 1
        }
        echo "OK, created succesfully." >&2
        return
}

create_user()
{
        echo -n "Checking user ${DRWEBUSER}: "
       
        userinfo -e ${DRWEBUSER} && {
                echo "OK, user already exists." >&2
                return
        }
        echo -n "user does not exist. Creating... "
        useradd -c "DrWeb Antivirus" -d /var/empty -g ${DRWEBGROUP} -s /sbin/nologin -u ${DRWEBID} ${DRWEBUSER} || {
                echo "ERR, cannot add user to database" >&2
                exit 1
        }
        echo "OK, created successfully." >&2
        return
}

extra()
{

}

do_notice()
{
        echo "----------------"
        echo "drweb-smf is almost installed"
	echo "----------------"
        echo
	echo "drweb_smf.conf, users.conf, addresses.conf, viruses.conf"
	echo "have been placed in ${PREFIX}/share/examples/drweb-clients"
	echo "they should be configured and placed into ${SYSCONFDIR}/drweb"
	echo
	echo "User/Group _drweb has been created. Use them."
	echo 
	echo "In order to run drweb-smf at boot time"
	echo "Add the following to /etc/rc.conf.local:"
	echo "+-------------"
	echo "drweb_smf=\"\"		# for normal use: \"\""
	echo "+------------"
	echo
	echo "Add to sendmail.mc:"
	echo "INPUT_MAIL_FILTER(\`drweb-filter', \`S=inet:3001@localhost, T=C:1m;S:5m;R:5m;E:1h')dnl" 
	echo "Read ${PREFIX}/share/doc/drweb-clients/sendmail for greater details"
	echo
	echo "Finally, add the following to /etc/rc.local:" 
	echo "+--------------";
	echo "if [ -f /etc/drweb/drweb_smf.conf -a X\"\${drweb_smf}\" != X\"NO\" ]; then"
	echo "	echo -n ' drweb-smf'; ${PREFIX}/drweb/bin/drweb-smf \${drweb_smf}"
	echo "fi"
	echo "+--------------"
}

# verify proper execution
#
if [ $# -ne 2 ]; then
	echo "usage: $0 distname { PRE-INSTALL | POST-INSTALL }" >&2
	exit 1
fi

# Verify/process the command
#
case $2 in
	PRE-INSTALL)
		: nothing to pre-install for this port
		;;
	POST-INSTALL)
		create_group
		create_user
		extra
		do_notice
		;;
	*)
		echo "usage: $0 distname { PRE-INSTALL | POST-INSTALL }" >&2
		exit 1
		;;
esac

exit 0


