#	$RuOBSD: Makefile,v 1.1.1.1 2001/11/14 13:14:21 form Exp $

LIB=	alias
SRCS=	alias.c alias_cuseeme.c alias_db.c alias_ftp.c alias_irc.c alias_nbt.c
SRCS+=	alias_pptp.c alias_proxy.c alias_smedia.c alias_util.c

COPTS=	-Wall -Werror -DNO_FW_PUNCH
NOPROFILE=
NOPIC=
NOLINT=

install:

.include <bsd.lib.mk>
