# $RuOBSD: GNUmakefile,v 1.1 2004/04/02 14:53:00 form Exp $

all:
	$(MAKE) -C cnupm
	$(MAKE) -C cnupmstat

clean:
	$(MAKE) -C cnupm clean
	$(MAKE) -C cnupmstat clean

install:
	$(MAKE) -C cnupm install
	$(MAKE) -C cnupmstat install

depend:
