#!/bin/sh
# $RuOBSD: DEINSTALL,v 1.2 2003/12/17 05:08:43 form Exp $
#
# ircd-hybrid de-installation

set -e
PATH=/bin:/usr/bin:/sbin:/usr/sbin
PREFIX=${PKG_PREFIX:-/usr/local}
CONFIG_DIR=${SYSCONFDIR}/ircd

if [ -d ${CONFIG_DIR} ]; then
	echo
	echo "+---------------"
	echo "| To completely deinstall the $1 package you need to perform"
	echo "| these step as root:"
	echo "|"
	echo "|           rm -rf ${CONFIG_DIR}"
	echo "|           userdel ircd"
	echo "|           groupdel ircd"
	echo "|"
	echo "| Do not do this if you plan on re-installing $1"
	echo "| at some future time."
	echo "+---------------"
	echo
fi

exit 0
