#!/bin/sh
# $RuOBSD: INSTALL,v 1.1.1.1 2002/03/03 09:38:35 grange Exp $
#
# Pre/post-installation setup of ircd-hybrid

# exit on errors, use a sane path and install prefix
#
set -e
PATH=/bin:/usr/bin:/sbin:/usr/sbin
PREFIX=${PKG_PREFIX:-/usr/local}
CONFIG_DIR=${SYSCONFDIR}/ircd
LOG_DIR=${CONFIG_DIR}/logs
SAMPLE_CONFIG_DIR=${PREFIX}/share/examples/ircd

do_notice()
{
	echo
	echo "+---------------"
	echo "| The existing $1 configuration files in ${CONFIG_DIR},"
	echo "| have NOT been changed. You may want to compare them to the"
	echo "| current sample files in ${SAMPLE_CONFIG_DIR},"
	echo "| and update your configuration as needed."
	echo "+---------------"
	echo
}

do_install()
{
	install -o root -g wheel -m 750 -d ${CONFIG_DIR}
	install -o root -g wheel -m 640 ${SAMPLE_CONFIG_DIR}/simple.conf \
		${CONFIG_DIR}/ircd.conf
	install -o root -g wheel -m 644 ${SAMPLE_CONFIG_DIR}/opers.txt \
		${CONFIG_DIR}
	install -o root -g wheel -m 640 /dev/null ${CONFIG_DIR}/kline.conf
	install -o root -g wheel -m 770 -d ${LOG_DIR}
	echo
	echo "+---------------"
	echo "| The $1 configuration files have been installed"
	echo "| into ${CONFIG_DIR}. Please view these files and change"
	echo "| the configuration to meet your needs."
	echo "+---------------"
	echo
}

# verify proper execution
#
if [ $# -ne 2 ]; then
	echo "usage: $0 distname { PRE-INSTALL | POST-INSTALL }" >&2
	exit 1
fi

# Verify/process the command
#
case $2 in
	PRE-INSTALL)
		: nothing to pre-install for this port
		;;
	POST-INSTALL)
		if [ -d ${CONFIG_DIR} ]; then
			do_notice $1
		else
			do_install $1
		fi
		;;
	*)
		echo "usage: $0 distname { PRE-INSTALL | POST-INSTALL }" >&2
		exit 1
		;;
esac

exit 0
