# $RuOBSD: BSDmakefile,v 1.3 2004/04/19 13:47:35 form Exp $

LIB=	cnupm
SRCS=	cnupm_daemon.c cnupm_family.c cnupm_pidfile.c cnupm_progname.c
SRCS+=	cnupm_protocol.c cnupm_restrict.c cnupm_ulval.c cnupm_version.c

NOPIC=
NOPROFILE=

.include "${.CURDIR}/../BSDosdefs.inc"

install:

.include <bsd.lib.mk>
