#!/bin/sh
# $RuOBSD$
#
# eggdrop de-installation

set -e
PATH=/bin:/usr/bin:/sbin:/usr/sbin
PREFIX=${PKG_PREFIX:-/usr/local}
EGGDROPDIR=/var/eggdrop

if [ -d $EGGDROPDIR ]; then
	echo
	echo "+---------------"
	echo "| To completely deinstall the $1 package you need to perform"
	echo "| this step as root:"
	echo "|"
	echo "|           rm -rf $EGGDROPDIR"
	echo "|"
	echo "| Do not do this if you plan on re-installing $1"
	echo "| at some future time."
	echo "+---------------"
	echo
fi

exit 0
