#!/bin/sh
# $RuOBSD$
#
# Pre/post-installation setup of eggdrop

set -e
PATH=/bin:/usr/bin:/sbin:/usr/sbin
PREFIX=${PKG_PREFIX:-/usr/local}
EGGDROPDIR=/var/eggdrop

do_notice()
{
	echo
	echo "+---------------"
	echo "| The existing $1 files in $EGGDROPDIR directory"
	echo "| has NOT been changed. You may want to compare it to the"
	echo "| sample files in $PREFIX/eggdrop and update your "
	echo "| configuration as needed."
	echo "+---------------"
	echo
}

do_usergroup()
{
	# Create eggdrop user and group
	if groupinfo -e eggdrop; then
		echo "===> Using 'eggdrop' group for $1"
	else
		echo "===> Creating 'eggdrop' group for $1"
		groupadd eggdrop
	fi
	if userinfo -e eggdrop; then
		echo "===> Using 'eggdrop' user for $1"
	else
		echo "===> Creating 'eggdrop' user for $1"
		useradd -g eggdrop -d /var/eggdrop -c 'EggDrop IRC Bot' \
			-s /sbin/nologin eggdrop
	fi
}

do_install()
{
	install -d -o eggdrop -g eggdrop -m 750 ${EGGDROPDIR}
	install -d -o eggdrop -g eggdrop -m 755 ${EGGDROPDIR}/text
	install -d -o eggdrop -g eggdrop -m 755 ${EGGDROPDIR}/logs
	install -d -o eggdrop -g eggdrop -m 755 ${EGGDROPDIR}/filesys
	install -d -o eggdrop -g eggdrop -m 755 ${EGGDROPDIR}/filesys/incoming
	install -o eggdrop -g eggdrop -m 644 \
		${PREFIX}/eggdrop/text/* ${EGGDROPDIR}/text
	install -o eggdrop -g eggdrop -m 644 ${PREFIX}/eggdrop/*.conf \
		${EGGDROPDIR}
	echo
	echo "+---------------"
	echo "| Sample $1 configuration files installed in $EGGDROPDIR."
	echo "| Please view these files and change the configuration"
	echo "| to meet your needs."
	echo "+---------------"
	echo
}

# Verify/process the command
#
case $2 in 
	PRE-INSTALL)
		if [ -d $EGGDROPDIR ]; then
			do_notice $1
		fi
		do_usergroup $1
		;;
	POST-INSTALL)
		if [ ! -d $EGGDROPDIR ]; then
			do_install $1
		fi
		;;
	*)
		echo "usage: $0 distname { PRE-INSTALL | POST-INSTALL }" >&2
		exit 1
		;;  
esac

exit 0
