# $RuOBSD: Makefile,v 1.1.1.1 2002/12/16 06:12:36 grange Exp $

PROG=	mail.buhal
SRCS=	mail.buhal.c
MAN=

COPTS=	-Wall -Werror -Wtraditional -ansi -pedantic

BINDIR?=/usr/local/libexec

.include <bsd.prog.mk>
