# $RuOBSD$

LIB=	nickdb
SRCS=	nickdb_add.c nickdb_aflags.c nickdb_auth.c nickdb_close.c \
	nickdb_creat.c nickdb_del.c nickdb_find.c nickdb_flags.c \
	nickdb_open.c nickdb_passwd.c nickdb_sync.c nickdb_update.c

.include <bsd.lib.mk>
