# $RuOBSD: Makefile,v 1.2 2010/11/01 18:18:45 dinar Exp $ 

     SUBDIR += converters
     SUBDIR += devel
     SUBDIR += emulators
     SUBDIR += mail
     SUBDIR += net
     SUBDIR += security
     SUBDIR += sysutils
     SUBDIR += www
     SUBDIR += x11

.include <bsd.port.subdir.mk>
