# $RuOBSD: Makefile,v 1.1.1.1 2010/11/01 16:36:05 dinar Exp $ 

     SUBDIR += devel
     SUBDIR += emulators
     SUBDIR += mail
     SUBDIR += net
     SUBDIR += security
     SUBDIR += sysutils
     SUBDIR += www
     SUBDIR += x11

.include <bsd.port.subdir.mk>
